version: '3.8'
services:
  openldap:
    image: ${REGISTRY}osixia/openldap:1.4.0
    ports:
      - "389:389"
      - "636:636"
    deploy:
      mode: replicated
      placement:
        constraints:
          - "node.role==manager"
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 120s
      resources:
        limits:
          memory: ${default_container_memory}
    environment:
      LDAP_DOMAIN: gridsum.com
      LDAP_ADMIN_PASSWORD: ${nifi_ldap_admin_password}
    volumes:
    - openldap-data-volume:/var/lib/ldap
    - openldap-config-volume:/etc/ldap/slapd.d
    networks:
      ddc_network:
        aliases:
          - openldap
  ldapadmin:
    image: ${REGISTRY}osixia/phpldapadmin
    ports:
      - "28080:80"
    deploy:
      mode: replicated
      placement:
        constraints:
          - "node.role==manager"
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 120s
      resources:
        limits:
          memory: ${default_container_memory}
    environment:
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
    networks:
      ddc_network:
        aliases:
          - ldapadmin
  nifi1:
    image: ${REGISTRY}${nifi_image}
    deploy:
      mode: replicated
      placement:
        constraints:
          - "node.labels.nodename==manager1"
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 120s
      resources:
        limits:
          memory: ${nifi_container_memory}
    hostname: nifi1
    volumes:
      - nifi1_logs_volume:/opt/nifi/nifi-current/logs
      - nifi1_config_volume:/opt/nifi/nifi-current/conf
      - nifi1_state_volume:/opt/nifi/nifi-current/state
      - nifi1_database_repository_volume:/opt/nifi/nifi-current/database_repository
      - nifi1_flowfile_repository_volume:/opt/nifi/nifi-current/flowfile_repository
      - nifi1_content_repository_volume:/opt/nifi/nifi-current/content_repository
      - nifi1_provenance_repository_volume:/opt/nifi/nifi-current/provenance_repository
    environment:
      NODE_HOST: nifi1
      NIFI_CLUSTER_NODE_ADDRESS: nifi1
      HTTPS_PORT: 8443
      LDAP_MANAGER_DN: "cn=admin,dc=gridsum,dc=com"
      LDAP_MANAGER_PASSWORD: ${nifi_ldap_admin_password}
      LDAP_USER_SEARCH_BASE: "dc=gridsum,dc=com"
    networks:
      ddc_network:
        aliases:
          - nifi1
  nifi2:
    image: ${REGISTRY}${nifi_image}
    deploy:
      mode: replicated
      placement:
        constraints:
          - "node.labels.nodename==manager2"
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 120s
      resources:
        limits:
          memory: ${nifi_container_memory}
    hostname: nifi2
    volumes:
      - nifi2_logs_volume:/opt/nifi/nifi-current/logs
      - nifi2_config_volume:/opt/nifi/nifi-current/conf
      - nifi2_state_volume:/opt/nifi/nifi-current/state
      - nifi2_database_repository_volume:/opt/nifi/nifi-current/database_repository
      - nifi2_flowfile_repository_volume:/opt/nifi/nifi-current/flowfile_repository
      - nifi2_content_repository_volume:/opt/nifi/nifi-current/content_repository
      - nifi2_provenance_repository_volume:/opt/nifi/nifi-current/provenance_repository
    environment:
      NODE_HOST: nifi2
      NIFI_CLUSTER_NODE_ADDRESS: nifi2
      HTTPS_PORT: 8443
      LDAP_MANAGER_DN: "cn=admin,dc=gridsum,dc=com"
      LDAP_MANAGER_PASSWORD: ${nifi_ldap_admin_password}
      LDAP_USER_SEARCH_BASE: "dc=gridsum,dc=com"
    networks:
      ddc_network:
        aliases:
          - nifi2
  nifi3:
    image: ${REGISTRY}${nifi_image}
    deploy:
      mode: replicated
      placement:
        constraints:
          - "node.labels.nodename==manager3"
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 120s
      resources:
        limits:
          memory: ${nifi_container_memory}
    hostname: nifi3
    volumes:
      - nifi3_logs_volume:/opt/nifi/nifi-current/logs
      - nifi3_config_volume:/opt/nifi/nifi-current/conf
      - nifi3_state_volume:/opt/nifi/nifi-current/state
      - nifi3_database_repository_volume:/opt/nifi/nifi-current/database_repository
      - nifi3_flowfile_repository_volume:/opt/nifi/nifi-current/flowfile_repository
      - nifi3_content_repository_volume:/opt/nifi/nifi-current/content_repository
      - nifi3_provenance_repository_volume:/opt/nifi/nifi-current/provenance_repository
    environment:
      NODE_HOST: nifi3
      NIFI_CLUSTER_NODE_ADDRESS: nifi3
      HTTPS_PORT: 8443
      LDAP_MANAGER_DN: "cn=admin,dc=gridsum,dc=com"
      LDAP_MANAGER_PASSWORD: ${nifi_ldap_admin_password}
      LDAP_USER_SEARCH_BASE: "dc=gridsum,dc=com"
    networks:
      ddc_network:
        aliases:
          - nifi3


volumes:
  openldap-data-volume:
  openldap-config-volume:
  nifi1_logs_volume:
  nifi1_config_volume:
  nifi1_state_volume:
  nifi1_database_repository_volume:
  nifi1_flowfile_repository_volume:
  nifi1_content_repository_volume:
  nifi1_provenance_repository_volume:
  nifi2_logs_volume:
  nifi2_config_volume:
  nifi2_state_volume:
  nifi2_database_repository_volume:
  nifi2_flowfile_repository_volume:
  nifi2_content_repository_volume:
  nifi2_provenance_repository_volume:
  nifi3_logs_volume:
  nifi3_config_volume:
  nifi3_state_volume:
  nifi3_database_repository_volume:
  nifi3_flowfile_repository_volume:
  nifi3_content_repository_volume:
  nifi3_provenance_repository_volume:
networks:
  ddc_network:
    external: true
    name: ${NETWORK}