version: '3.8'
services:
  nginx:
    image: ${REGISTRY}${nginx_image}
    ports:
      - "8443:8443"
    volumes:
      - nginx-logs-volume:/var/log/nginx
    networks:
      ddc_network:
        aliases:
          - nginx
volumes:
  nginx-logs-volume:
networks:
  ddc_network:
    external: true
    name: ${NETWORK}