version: '3.8'
services:
  nginx:
    image: ${REGISTRY_HOST}${nginx_image}
    ports:
      - "8443:8443"
    networks:
      - ddc_network
networks:
  ddc_network:
    external: true
    name: ${NETWORK}