version: '3.8'
services:
  mysql:
    image: ${REGISTRY}${mysql_image}
    logging:
      driver: "json-file"
      options:
        max-size: ${CONTAINER_LOG_SIZE}
        max-file: ${CONTAINER_LOG_NUMS}
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=${mysql_max_connections}
    ports:
      - "3306:3306"
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.nodename==${NODE2_TAG}
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 120s
    environment:
      MYSQL_DATABASE: auth
      MYSQL_ROOT_PASSWORD: ${mysql_root_passwd}
      MYSQL_ROOT_HOST: '%'
      TZ: "Asia/Shanghai"
    volumes:
      - mysql-data-volume:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      ddc_network:
        aliases:
          - mysql

volumes:
  mysql-data-volume:
networks:
  ddc_network:
    external: true
    name: ${NETWORK}