version: '3.8'
services:
  server:
    image: ${REGISTRY}${MICRO_SERVER}:${MICRO_VERSION}
    logging:
      driver: "json-file"
      options:
        max-size: ${CONTAINER_LOG_SIZE}
        max-file: ${CONTAINER_LOG_NUMS}
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.nodename==${NODE3_TAG}
#      placement:
#        constraints:
#          - "node.role==worker"
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 120s
      resources:
        limits:
          memory: ${default_container_memory}
    environment:
      TZ: "Asia/Shanghai"
      JVM_ARG_1: "-Xmx512m"
      JVM_ARG_2: "-Xms512m"
      JVM_ARG_3: "-XX:+UseConcMarkSweepGC"
      JVM_ARG_4: "-XX:+UseParNewGC"
      JVM_ARG_5: "-XX:CMSInitiatingOccupancyFraction=75"
      JVM_ARG_7: "-XX:CMSMaxAbortablePrecleanTime=5000"
    command: ${MICRO_COMMAND}
    volumes:
      - app-logs-volume:/opt/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      ddc_network:
        aliases:
          - ${MICRO_SERVER}

volumes:
  app-logs-volume:
networks:
  ddc_network:
    external: true
    name: ${NETWORK}