version: '3.8'
services:
  kafka1:
    image: ${REGISTRY}${kafka_image}
    ports:
      - target: ${kafka_out_port}
        published: ${kafka_out_port}
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.nodename==${NODE1_TAG}
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 120s
      resources:
        limits:
          memory: ${kafka_container_memory}
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://${NODE1_IP}:${kafka_out_port}
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:${kafka_out_port}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    volumes:
      - kafka1-data-volume:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ddc_network:
        aliases:
          - kafka1
  kafka2:
    image: ${REGISTRY}${kafka_image}
    ports:
      - target: ${kafka_out_port}
        published: ${kafka_out_port}
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.nodename==${NODE2_TAG}
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 120s
      resources:
        limits:
          memory: ${kafka_container_memory}
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://${NODE2_IP}:${kafka_out_port}
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:${kafka_out_port}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    volumes:
      - kafka2-data-volume:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ddc_network:
        aliases:
          - kafka2
  kafka3:
    image: ${REGISTRY}${kafka_image}
    ports:
      - target: ${kafka_out_port}
        published: ${kafka_out_port}
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.nodename==${NODE3_TAG}
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 120s
      resources:
        limits:
          memory: ${kafka_container_memory}
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://${NODE3_IP}:${kafka_out_port}
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:${kafka_out_port}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    volumes:
      - kafka3-data-volume:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ddc_network:
        aliases:
          - kafka3
volumes:
  kafka1-data-volume:
  kafka2-data-volume:
  kafka3-data-volume:
networks:
  ddc_network:
    external: true
    name: ${NETWORK}
