version: '3.8'
services:
  kafka1:
    image: ${kafka_image}
    ports:
      - 9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    # KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://192.168.33.22:9094
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFAK_NUM_PARTITION: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    volumes:
      - kafka1-data-volume:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ddc_network:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          memory: 2048M
  kafka2:
    image: ${kafka_image}
    ports:
      - 9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      # KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://192.168.33.22:9094
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFAK_NUM_PARTITION: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    volumes:
      - kafka2-data-volume:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ddc_network:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          memory: 2048M
  kafka3:
    image: ${kafka_image}
    ports:
      - 9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      # KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://192.168.33.22:9094
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFAK_NUM_PARTITION: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    volumes:
      - kafka3-data-volume:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ddc_network:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          memory: 2048M
volumes:
  kafka1-data-volume:
  kafka2-data-volume:
  kafka3-data-volume:
networks:
  ddc_network:
    external: true
