version: '3.8'
services:

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - 9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      PORT_COMMAND: "docker port $$(hostname) 9092/tcp | cut -d: -f2"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.33.22:_{PORT_COMMAND}
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - kafka-data-volume:/kafka
      -  /var/run/docker.sock:/var/run/docker.sock
    networks:
      ddc_network:
volumes:
  zoo1-data-volume:
  zoo1-datalog-volume:
  zoo1-log-volume:
  zoo2-data-volume:
  zoo2-datalog-volume:
  zoo2-log-volume:
  zoo3-data-volume:
  zoo3-datalog-volume:
  zoo3-log-volume:
  kafka-data-volume: 
networks:
  ddc_network: