version: '3.8'
services:
  mongodb1:
    image: gridsum/mongo:4.2.8
    volumes:
      - mongo1-data-volume:/data/db
      - mongo1-config-volume:/data/configdb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWD}
    networks: 
      - ddc_network
    entrypoint:
      - docker-entrypoint.sh
      - mongod
      - --replSet
      - rs
      - --keyFile
      - /data/mongodb.key
  mongodb2:
    image: gridsum/mongo:4.2.8
    volumes:
      - mongo2-data-volume:/data/db
      - mongo2-config-volume:/data/configdb
    ports:
      - 27018:27017
    depends_on:
      - mongodb1
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWD}
    networks:
      - ddc_network
    entrypoint:
      - docker-entrypoint.sh
      - mongod
      - --replSet
      - rs
      - --keyFile
      - /data/mongodb.key
  mongodb3:
    image: gridsum/mongo:4.2.8
    volumes:
      - mongo3-data-volume:/data/db
      - mongo2-config-volume:/data/configdb
    ports:
      - 27019:27017
    depends_on:
      - mongodb1
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWD}
    networks:
      - ddc_network
    entrypoint:
      - docker-entrypoint.sh
      - mongod
      - --replSet
      - rs
      - --keyFile
      - /data/mongodb.key
volumes:
  mongo1-data-volume:
  mongo1-config-volume:
  mongo2-data-volume:
  mongo2-config-volume:
  mongo3-data-volume:
  mongo3-config-volume:
networks:
  ddc_network:
    external: true