version: '3.8'
services:
  mongodb1:
    image: mongo
    restart: always
    container_name: mongo1
    volumes:
      - mongo1-data-volume:/data/db
      - /opt/mongodb/mongodb.key:/data/mongodb.key
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks: 
      - mongoNet
    command: mongod --replSet rs --keyFile /data/mongodb.key
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh $$@
  mongodb2:
    image: mongo
    restart: always
    container_name: mongo2
    volumes:
        - mongo2-data-volume:/data/db
        - /opt/mongodb/mongodb.key:/data/mongodb.key
    ports:
        - 27018:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
    networks:
        - mongoNet
    command: mongod --replSet rs --keyFile /data/mongodb.key
    entrypoint:
        - bash
        - -c
        - |
          chmod 400 /data/mongodb.key
          chown 999:999 /data/mongodb.key
          exec docker-entrypoint.sh $$@
  mongodb3:
    image: mongo
    restart: always
    container_name: mongo3
    volumes:
        - mongo3-data-volume:/data/db
        - /opt/mongodb/mongodb.key:/data/mongodb.key
    ports:
        - 27019:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
    networks:
        - mongoNet
    command: mongod --replSet rs --keyFile /data/mongodb.key
    entrypoint:
        - bash
        - -c
        - |
          chmod 400 /data/mongodb.key
          chown 999:999 /data/mongodb.key
          exec docker-entrypoint.sh $$@
  repliSet:
    image: mongo
    networks:
      - mongoNet
    entrypoint:
      - "mongo"
    command: --host mongo1 --username root --password root \
     --eval 'config={"_id":"rs","members":[{"_id":0,"host":"mongo1:27017"},\
     {"_id":1,"host":"mongo2:27017"},{"_id":2,"host":"mongo3:27017"}]};\
     rs.initiate(config);'   
    depends_on: 
      - mongodb1
      - mongodb2
      - mongodb3  
        
volumes: 
  mongo1-data-volume:
  mongo2-data-volume:
  mongo3-data-volume:
  
networks:
  mongoNet:
    driver: bridge