version: '3.8'
services:
  redis1:
    image: ${REGISTRY_HOST}${redis_image}
    ports:
      - 6379:6379
    environment:
      PASSWORD: ${redis_password}
    volumes:
      - redis1-volume:/data
    networks:
      ddc_network:
  redis2:
    image: ${REGISTRY_HOST}${redis_image}
    ports:
      - 6380:6379
    depends_on:
      - redis1
    environment:
      PASSWORD: ${redis_password}
      SLAVEOF: "redis1 6379"
    volumes:
      - redis2-volume:/data
    networks:
      ddc_network:
  redis3:
    image: ${REGISTRY_HOST}${redis_image}
    ports:
      - 6381:6379
    depends_on:
      - redis1
    environment:
      PASSWORD: ${redis_password}
      SLAVEOF: "redis1 6379"
    volumes:
      - redis3-volume:/data
    networks:
      ddc_network:
  sentinel1:
    image: ${REGISTRY_HOST}${redis_image}
    environment:
      PORT: 26379
      SENTINEL_MASTER: "redis1 6379 2"
      SENTINEL_AUTHPASS: ${redis_password}
    command: redis-sentinel
    depends_on:
      - redis1
      - redis2
      - redis3
    volumes:
      - sentinel1-volume:/data
    networks:
      ddc_network:
  sentinel2:
    image: ${REGISTRY_HOST}${redis_image}
    environment:
      PORT: 26379
      SENTINEL_MASTER: "redis1 6379 2"
      SENTINEL_AUTHPASS: ${redis_password}
    command: redis-sentinel
    depends_on:
      - redis1
      - redis2
      - redis3
    volumes:
      - sentinel2-volume:/data
    networks:
      ddc_network:
  sentinel3:
    image: ${REGISTRY_HOST}${redis_image}
    environment:
      PORT: 26379
      SENTINEL_MASTER: "redis1 6379 2"
      SENTINEL_AUTHPASS: ${redis_password}
    command: redis-sentinel
    depends_on:
      - redis1
      - redis2
      - redis3
    volumes:
      - sentinel3-volume:/data
    networks:
      ddc_network:


volumes:
  redis1-volume:
  redis2-volume:
  redis3-volume:
  sentinel1-volume:
  sentinel2-volume:
  sentinel3-volume:
networks:
  ddc_network:
    external: true
    name: ${NETWORK}