version: '3.8'
services:
  redis1:
    image: gridsum/redis:5.0.9
    ports:
      - 6379:6379
    environment:
      PASSWORD: "123456"
    volumes:
      - redis1-volume:/data
    networks:
      ddc-network:
  redis2:
    image: gridsum/redis:5.0.9
    ports:
      - 6380:6379
    environment:
      PASSWORD: "123456"
      SLAVEOF: "redis1 6379"
    volumes:
      - redis2-volume:/data
    networks:
      ddc-network:
  redis3:
    image: gridsum/redis:5.0.9
    ports:
      - 6381:6379
    environment:
      PASSWORD: "123456"
      SLAVEOF: "redis1 6379"
    volumes:
      - redis3-volume:/data
    networks:
      ddc-network:
  sentinel1:
    image: gridsum/redis:5.0.9
    ports:
      - 6379
    environment:
      PORT: 26379
      SENTINEL_NAME: "mymaster"
      SENTINEL_MASTER: "redis1 6379 2"
      SENTINEL_AUTHPASS: "123456"
    volumes:
      - sentinel1-volume:/data
    networks:
      ddc-network:
  sentinel2:
    image: gridsum/redis:5.0.9
    ports:
      - 6379
    environment:
      PORT: 26379
      SENTINEL_NAME: "mymaster"
      SENTINEL_MASTER: "redis1 6379 2"
      SENTINEL_AUTHPASS: "123456"
    volumes:
      - sentinel2-volume:/data
    networks:
      ddc-network:
  sentinel3:
    image: gridsum/redis:5.0.9
    ports:
      - 6379
    environment:
      PORT: 26379
      SENTINEL_NAME: "mymaster"
      SENTINEL_MASTER: "redis1 6379 2"
      SENTINEL_AUTHPASS: "123456"
    volumes:
      - sentinel3-volume:/data
    networks:
      ddc-network:


volumes:
  redis1-volume:
  redis2-volume:
  redis3-volume:
  sentinel1-volume:
  sentinel2-volume:
  sentinel3-volume:
networks:
  ddc-network:
    external: true